CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL
);

CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(64) NOT NULL,
    last_name VARCHAR(64) NOT NULL,
    position VARCHAR(64) NOT NULL,
    salary INT NOT NULL,
    department_id BIGINT NOT NULL,
    CONSTRAINT fk_employees_departments FOREIGN KEY (department_id) REFERENCES departments(id)
);
